In [2]:
print("Ques 1.")
import numpy as np

arr=np.array([1,2,3,4,5])
print("original array:",arr)
print("after adding 2 :",arr+2)
print("after dividing by 2 ",arr/2)
print("after multiplying by 3 ",arr*3)
print("Done")



Ques 1.
original array: [1 2 3 4 5]
after adding 2 : [3 4 5 6 7]
after dividing by 2  [0.5 1.  1.5 2.  2.5]
after multiplying by 3  [ 3  6  9 12 15]
Done


In [16]:
print("Ques 2a.")
import numpy as np
arr0 = np.array([1, 2, 3, 6, 4, 5])
print("reversed array \n", arr0[::-1])#indexing
print("\nQues 2b.")
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])
print("maximum frequent value in x :",np.bincount(x).argmax(), "maximum frequent value in y :",np.bincount(y).argmax())


Ques 2a.
reversed array 
 [5 4 6 3 2 1]

Ques 2b.
maximum frequent value in x : 1 maximum frequent value in y : 1


In [19]:
print("Ques 3.")
import numpy as np
arr1 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("1st row , 2nd column element : ",arr1[0, 1],"\n3rd row , 1st column element:", arr1[2, 0])


Ques 3.
1st row , 2nd column element :  20 
3rd row , 1st column element: 70


In [20]:
print("Ques4.")
import numpy as np
tanveer_array = np.linspace(10, 100, 25)
print(tanveer_array.shape)
print(tanveer_array.size)
print(tanveer_array.dtype)
print(tanveer_array.nbytes)
print(tanveer_array.reshape(25, 1).T)


Ques4.
(25,)
25
float64
200
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]


In [21]:
print("Ques 5.")
import numpy as np
UCS420_TANVEER= np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print(np.mean(UCS420_TANVEER))
print(np.median(UCS420_TANVEER))
print(np.max(UCS420_TANVEER))
print(np.min(UCS420_TANVEER))
print(np.unique(UCS420_TANVEER))
reshaped_ucs420 = UCS420_TANVEER.reshape(4, 3)
resized_ucs420 = np.resize(UCS420_TANVEER, (2, 3))
print(reshaped_ucs420, resized_ucs420)

Ques 5.
43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]] [[10 20 30]
 [40 50 60]]
